---
# Python 3 with PostgreSQL
version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile    
    hostname: nyu
    container_name: recommendations
    volumes:
      - ..:/app
      - ~/.bluemix/apikey.json:/home/vscode/.bluemix/apikey.json
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      FLASK_DEBUG: True
      PORT: 8000
      #GUNICORN_BIND: "0.0.0.0:8080"
      DATABASE_URI: postgresql://postgres:postgres@postgres:5432/postgres
    networks:
      - dev
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    # Uncomment ports to access database from your computer (optional)
    # ports:
    #   - 5432:5432

    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - dev

volumes:
  postgres:

networks:
  dev:
